require("nvim-treesitter.configs").setup({
    ensure_installed = {
        -- https://github.com/nvim-treesitter/nvim-treesitter?tab=readme-ov-file#available-modules
        "bash",
        "c",
        "css",
        "dockerfile",
        "git_config",
        "git_rebase",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "gotmpl",
        "gowork",
        "hcl",
        "helm",
        "html",
        "ini",
        "java",
        "javascript",
        "json",
        "lua",
        "make",
        "markdown",
        "proto",
        "python",
        "sql",
        "terraform",
        "tmux",
        "typescript",
        "xml",
        "yaml",
    },

    sync_install = false,
    auto_install = true,
    highlight = {
        enable = true,
    },
})
