[font]
size = 14.0

[font.normal]
family = "UbuntuMono Nerd Font"

# COLORS DEFAULTS
[colors.primary]
background = "#262626"
# background = "#2c2c2c"
foreground = "#d6d6d6"
dim_foreground = "#dbdbdb"
bright_foreground = "#d9d9d9"

[colors.cursor]
text = "#2c2c2c"
cursor = "#d9d9d9"

[colors.normal]
black = "#1c1c1c"
red = "#d04642"
# red = "#bc5653"
green = "#63cf7b"
# green = "#909d63"
yellow = "#ffa100"
# yellow = "#ebc17a"
blue = "#5aa5d7"
# blue = "#7eaac7"
magenta = "#c4539e"
# magenta = "#aa6292"
cyan = "#58dcd3"
# cyan = "#86d3ce"
white = "#cacaca"

[colors.bright]
black = "#636363"
red = "#bc5653"
green = "#909d63"
yellow = "#ebc17a"
blue = "#7eaac7"
magenta = "#aa6292"
cyan = "#86d3ce"
white = "#f7f7f7"

[colors.dim]
black = "#232323"
red = "#74423f"
green = "#5e6547"
yellow = "#8b7653"
# blue = "#556b79"
blue = "#3a769c"
magenta = "#6e4962"
# cyan = "#5c8482"
cyan = "#4a9490"
white = "#828282"

# [cursor.style]
# shape = "Beam"
# shape = "Block"
# [cursor.vi_mode_style]
# shape = "Block"

# --- colors
# https://github.com/alacritty/alacritty-theme
